package license

import (
	"crypto/ed25519"
	"encoding/json"
	"testing"
	"time"
)

// FuzzVerify hammers the one function in the program that parses bytes an
// attacker fully controls: a license file is just a file, and anyone can put
// anything in one. Two properties must hold for every input ever: Verify never
// panics, and it never accepts a license the real key did not sign. A success
// on fuzzer-generated bytes would be a signature forgery, which is the worst
// bug this package could possibly have.
func FuzzVerify(f *testing.F) {
	f.Add([]byte(""))
	f.Add([]byte("{"))
	f.Add([]byte("null"))
	f.Add([]byte(`{"license":{},"signature":""}`))
	f.Add([]byte(`{"license":{"id":"x","org":"y","tier":"memory"},"signature":"AAAA"}`))
	f.Add([]byte(`{"license":{"tier":"free","expires":"9999-12-31T00:00:00Z"},"signature":"!!!"}`))

	// A structurally perfect license signed by the WRONG key seeds the most
	// interesting corner: everything parses, only the signature is alien.
	_, wrongKey, err := ed25519.GenerateKey(nil)
	if err != nil {
		f.Fatalf("GenerateKey: %v", err)
	}
	forged, err := Sign(License{ID: "f", Org: "Forger", Tier: Memory, Issued: time.Now()}, wrongKey)
	if err != nil {
		f.Fatalf("Sign: %v", err)
	}
	f.Add(forged)

	now := time.Date(2026, 8, 17, 0, 0, 0, 0, time.UTC)
	f.Fuzz(func(t *testing.T, data []byte) {
		lic, err := Verify(data, now)
		if err == nil {
			pretty, _ := json.Marshal(lic)
			t.Fatalf("Verify accepted fuzzer-generated bytes as a real license: %s", pretty)
		}
	})
}
